boats_auth/urls.py
from django.conf.urls import url

from boats_auth import views

urlpatterns = [
    url(r'^login$', views.login_view, name='login_view'),
    url(r'^logout$', views.logout_view, name='logout_view'),
]

boats_estimator/urls.py
from django.conf.urls import include, url
from logic import urls as logic_urls
from logic.views import estimate_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^logic/', include(logic_urls, namespace='logic')),
    url(r'^$', estimate_view),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logic/urls.py
from django.conf.urls import url

from logic import views

urlpatterns = [
    url(r'^estimate$', views.estimate_view, name='estimate_view'),
    url(r'^plots$', views.plots_view, name='plots_view'),
]

boats_auth/models.py
from django.db import models


class VisitingDate(models.Model):

    def __str__(self):
        return '{}'.format(self.date)

    date = models.DateField(primary_key=True)


class VisitingIP(models.Model):

    def __str__(self):
        return self.ip_address

    ip_address = models.GenericIPAddressField(primary_key=True)


class Visitor(models.Model):

    def __str__(self):
            return 'IP: {} date: {}'.format(
                self.visiting_ip,
                self.visiting_date)

    visiting_ip = models.ForeignKey(VisitingIP)
    visiting_date = models.ForeignKey(VisitingDate)

logic/forms.py
import numpy as np
from django import forms


FEATURE_NAMES = np.load('logic/feature_names.npy')
BUILDER_NAMES = np.load('logic/builder_names.npy')
AVERAGES = np.load('logic/averages.npy').reshape(-1)[0]  # 'cause of numpy

MIN_DICT = np.load('logic/min_dict.npy').reshape(-1)[0]  # 'cause of numpy
MAX_DICT = np.load('logic/max_dict.npy').reshape(-1)[0]  # 'cause of numpy


def make_hr(builder_name):

    if builder_name == 'None':
        return 'Other'

    return builder_name.title()


class EstimateBoatForm(forms.Form):

    CHOICES = ((b, make_hr(b)) for b in BUILDER_NAMES)

    def __init__(self, *args, **kwargs):

        super(EstimateBoatForm, self).__init__(*args, **kwargs)

        for feature_name in FEATURE_NAMES:
            if not self.fields.get(feature_name, None):

                min = MIN_DICT[feature_name]
                max = MAX_DICT[feature_name]

                help_text = 'Range: {} to {}'.format(min, max)

                self.fields[feature_name] = forms.FloatField(
                    required=False,
                    help_text=help_text)

    def clean(self):

        for feature_name in FEATURE_NAMES:

            if not self.cleaned_data.get(feature_name, None):
                avg = AVERAGES[feature_name]
                self.cleaned_data[feature_name] = avg

            else:
                val = self.cleaned_data[feature_name]
                min = MIN_DICT[feature_name]
                max = MAX_DICT[feature_name]

                if val < min or val > max:
                    msg = 'Value must be in range '
                    msg += '[{}, {}]'.format(min, max)
                    self.add_error(feature_name, msg)

        return self.cleaned_data

    builder = forms.ChoiceField(choices=CHOICES)

boats_auth/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponseRedirect
from boats_auth import utils


def login_view(request):

    (next_view, next_url) = utils.get_next_view_and_url(request)

    if request.POST:

        form = AuthenticationForm()

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:

            login(request, user)

            return HttpResponseRedirect(reverse(next_view))

        else:

            messages.error(request, 'Invalid credentials.')

    else:

        form = AuthenticationForm()

    context = {'form': form,
               'next_url': next_url,
               'current_view': 'login_view'}

    return render(request, 'boats_auth/login.html', context)

            
def logout_view(request):

    logout(request)
    
    # messages.error(request, 'User logged out.')

    return HttpResponseRedirect(reverse('boats_auth:login_view'))

logic/views.py
from django.shortcuts import render
from django.contrib import messages
from boats_auth import utils as auth_utils
from logic import forms
from logic import utils as logic_utils


def estimate_view(request):

    auth_utils.register_ip_address(request)

    est_price_euro = None

    if request.POST:

        form = forms.EstimateBoatForm(request.POST)

        if form.is_valid():

            est_price_euro = logic_utils.estimate_asking_price_euro(
                form)

            messages.info(
                request,
                'Boat estimated at {:.0f} euro'.format(
                    est_price_euro))

        else:
            messages.info(request, 'Invalid input.')

    else:
        form = forms.EstimateBoatForm()

    context = {'form': form,
               'est_price_euro': est_price_euro,
               'current_view': 'estimate_view'}

    return render(request, 'logic/estimate.html', context)


def plots_view(request):

    context = {'current_view': 'plots_view'}
    return render(request, 'logic/plots.html', context)

boats_auth/templates/boats_auth/login.html
{% extends 'boats/base.html' %}

{% block content %}

<h1>Login</h1>

  <p>

    <form role="form"
	  class="table"
	  action="{% url 'boats_auth:login_view' %}?next={{ next_url }}"
	  method="POST">
      {% csrf_token %} 

      {% for field in form %}
      <fieldset class="form-group">
	<label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
	<div class="form-control">

	  {{ field }}

	</div>
      </fieldset>
      {% endfor %}

      <input type="submit" value="Submit"  class="btn btn-primary">
      <button type="reset" value="Reset" class="btn btn-warning">Reset</button>
    </form>

{% endblock %}

boats_estimator/templates/boats_estimator/base.html
<!DOCTYPE html>
<html lang="en" >

<meta name="Sailboat asking price estimator" content="Sailboat asking price estimator">
<meta http-equiv="content-type" content="text/html;charset=UTF-8">

  {% load staticfiles %}

  <head>

    <!-- Latest compiled and minified JavaScript -->
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/effect-ini.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

  </head>

  <body>

<div role="navigation">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="{% url 'logic:estimate_view' %}">
	  <span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
	  </a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <ul class="nav navbar-nav">

		{% if current_view = 'estimate_view' %}
                <li class="active"><a href="{% url 'logic:estimate_view' %}">Estimate</a></li>
		{% else %}
                <li><a href="{% url 'logic:estimate_view' %}">Estimate  <span class="sr-only">(current)</span></a></li>
		{% endif %}

		{% if current_view = 'plots_view' %}
                <li class="active"><a href="{% url 'logic:plots_view' %}">Plots <span class="sr-only">(current)</span></a></li>
		{% else %}
                <li><a href="{% url 'logic:plots_view' %}">Plots</a></li>
		{% endif %}


	  </ul>

	</div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
</div> 


{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

    {% block content %}
    {% endblock %}

  </body>

</html>

logic/templates/logic/estimate.html
{% extends 'boats_estimator/base.html' %}

{% block content %}

<h2>Asking price sailboat excessive?</h2>

Find out here,
based on hundreds of used sailboat adds. <br>
<p>
  Fill out the form below. <br>
<p>
  Not all fields are required, average values are used when needed.<br>

  {% if estimate %}

  <hr>

<p>
  Sailboat estimated at <b>{{ estimate }}</b> euros.
<p>

  {% endif %}

  <hr>

  <form role="form" class="table" action="{% url 'logic:estimate_view' %}" method="POST">
    
    {% csrf_token %}
    
    {% for field in form %}
    <fieldset class="form-group">
      <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
     
      <div class="form-control">
        {{ field }}
      </div>

      <div class="control-group warning">
        {% if field.errors %}
        {{ field.errors }}
        {% else %}
        {{ field.help_text }}
        {% endif %}
      </div>
      
    </fieldset>
    {% endfor %}
    <input type="submit" value="Submit"  class="btn btn-primary">
    <button type="reset" value="Reset" class="btn btn-warning">Reset</button>
  </form>


</div>

</form>

{% endblock %}

logic/templates/logic/plots.html
{% extends 'boats_estimator/base.html' %}

{% load static %}

{% block content %}


<h3>Distribution and scatter plots</h3>

<h3>Comparison Plots</h3>

{% endblock %}